debug:
	 cat ./logs/checkout/pickuppoint-cloud-dfewr3r.log | vector -c ./test.toml -v

test:
	vector --verbose test --config-toml ./test.toml

test1:
	vector --verbose test --config-toml ./test1.toml
