data_dir: /vector-data-dir
sources:
  stdin:
    type: stdin
transforms:
  json_parser:
    type: remap
    inputs:
      - stdin
    source: |-
      structured,err = parse_json(.message)
      . = merge!(., structured)
      .source_type = "json_parser"
sinks:
  stdout:
    type: console
    inputs: [ json_parser, stdin]
    encoding:
      codec: json
