---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: vector
  labels:
    app.kubernetes.io/component: Agent
    app.kubernetes.io/instance: vector
    app.kubernetes.io/name: vector
    app.kubernetes.io/version: 0.20.0-distroless-libc
