apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapp-deployment
  namespace: apps
  labels:
    app: simpleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpleapp
  template:
    metadata:
      labels:
        app: simpleapp
    spec:
      containers:
        - name: simpleapp
          image: simple-app:1.0
          ports:
            - containerPort: 8080
